// let number = Math.floor((Math.random()*100) + 1);
// console.log(number);

// MDn Math Class in Javascript

//Generates a Random Number between 1 and 100
let number = Math.floor((Math.random() * 100) + 1);
//alert(number);
//Initial value of chances taken to guess a number
let chances = 0;

//Variable to store the number to be input from user to be guessed
let guess;

console.log(`This is a guessing game and you have to enter a number `
+` and if it matches with the number generated by computer, then you win ... \n`);

guess = prompt(`Enter a Number between 1 and 100`);
++chances;
let arr =[];
arr.push(guess);

do {
    guess = Number.parseInt(guess);
    if (guess > number) {
        alert(`Number Entered is Greater `);
        guess = prompt(`Previous Guessed Number is `+ arr +` Enter Again!!!`);
        arr.push(guess);
        ++chances; // To increment the Number of chances taken
        guess = Number.parseInt(guess);
        continue;
    }
    else if(guess < number){
        alert(`Number Entered is Smaller `);
        guess = prompt(`Previous Guessed Number is `+ arr +` Enter Again!!!`);
        arr.push(guess);
        ++chances; // To increment the Number of chances taken
        guess = Number.parseInt(guess);
        continue;
    }
    
} while (guess != number); // break the loop if number enetered is equal to the number generated

let score = 100 - chances;// To store the score of your game
console.log(`\nCongratulations \n The Number Generated was `+number+` and you guessed it right\n Chances Taken is`+chances+` \n Your Final score is `+score);